# Generated by Django 5.1.2 on 2024-10-24 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usuariosrol_proyecto_alter_usuarios_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='progreso',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SubTareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=False)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tarea')),
            ],
        ),
    ]
