# Generated by Django 5.1.2 on 2024-11-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cargos_usuarios_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Progreso', 'En Progreso'), ('Completada', 'Completada'), ('Retrasada', 'Retrasada')], default='Pendiente', max_length=20),
        ),
    ]
